Transform: AWS::SecretsManager-2020-07-23
Description: database mysql by Secrets Manager
Resources:
  MyRDSInstanceRotationSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: This is my rds instance secret
      GenerateSecretString:
        SecretStringTemplate: '{"username": "admin"}'
        GenerateStringKey: password
        PasswordLength: 16
        ExcludeCharacters: '"@/\'
      Tags:
      - Key: AppName
        Value: MyApp
  MyDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: A2OnLineMainDB
      AllocatedStorage: 20
      DBInstanceClass: db.t2.micro
      Engine: mysql
      BackupRetentionPeriod: 1
      VPCSecurityGroups:
      - sg-0972b7aabb5370b44
      SourceRegion: us-east-1
      SourceDBInstanceIdentifier: arn:aws:rds:us-east-1:154096909498:db:a2onlinemaindb
  SecretRDSInstanceAttachment:
    Type: AWS::SecretsManager::SecretTargetAttachment
    Properties:
      SecretId:
        Ref: MyRDSInstanceRotationSecret
      TargetId:
        Ref: MyDBInstance
      TargetType: AWS::RDS::DBInstance
  MySecretRotationSchedule:
    Type: AWS::SecretsManager::RotationSchedule
    DependsOn: SecretRDSInstanceAttachment
    Properties:
      SecretId:
        Ref: MyRDSInstanceRotationSecret
      HostedRotationLambda:
        RotationType: MySQLSingleUser
        RotationLambdaName: SecretsManagerRotation
        VpcSubnetIds: subnet-17209e71
      RotationRules:
        AutomaticallyAfterDays: 30
