---
Transform: AWS::SecretsManager-2020-07-23
Description: database mysql by Secrets Manager
Resources:

  
  #This is the VPC that the rotation Lambda function and the RDS instance will be placed in
  # DBVPC:
  #   Type: AWS::EC2::VPC
  #   Properties:
  #     CidrBlock: 172.31.64.0/16
  #     EnableDnsHostnames: true
  #     EnableDnsSupport: true
  # # vpc-06db0e60    
      
  # InstanceSecurityGroup:
  #   Type: AWS::EC2::SecurityGroup
  #   Properties:
  #     GroupDescription: Allow 3306 to client host
  #     VpcId:
  #        Ref: DBVPC
  #     SecurityGroupIngress:
  #     - IpProtocol: tcp
  #       FromPort: 3306
  #       ToPort: 3306
  #       CidrIp: 0.0.0.0/0
  #     SecurityGroupEgress:
  #     - IpProtocol: tcp
  #       FromPort: 3306
  #       ToPort: 3306
  #       CidrIp: 0.0.0.0/0

  # Subnet that the rotation Lambda function and the RDS instance will be placed in 
  # DBSubnet01:
  #   Type: AWS::EC2::Subnet
  #   Properties:
  #     CidrBlock: 172.31.96.0/19
  #     AvailabilityZone:
  #       Fn::Select:
  #       - '0'
  #       - Fn::GetAZs:
  #           Ref: AWS::Region
  #     VpcId:
  #       Ref: DBVPC
  # DBSubnet02:
  #   Type: AWS::EC2::Subnet
  #   Properties:
  #     CidrBlock: 172.31.128.0/19
  #     AvailabilityZone:
  #       Fn::Select:
  #       - '1'
  #       - Fn::GetAZs:
  #           Ref: AWS::Region
  #     VpcId:
  #       Ref: DBVPC
        #subnet-17209e71
  #VPC endpoint that will enable the rotation Lambda function to make api calls to Secrets Manager 
  # SecretsManagerVPCEndpoint:
  #   Type: AWS::EC2::VPCEndpoint
  #   Properties:
  #     SubnetIds:
  #     - subnet-17209e71
  #     VpcEndpointType: Interface
  #     ServiceName:
  #       Fn::Sub: com.amazonaws.${AWS::Region}.secretsmanager
  #     PrivateDnsEnabled: true
  #     VpcId: vpc-06db0e60
  
  #This is a Secret resource with a randomly generated password in its SecretString JSON.
  MyRDSInstanceRotationSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: This is my rds instance secret
      GenerateSecretString:
        SecretStringTemplate: '{"username": "admin"}'
        GenerateStringKey: password
        PasswordLength: 16
        ExcludeCharacters: "\"@/\\"
      Tags:
      - Key: AppName
        Value: MyApp
        
  #This is an RDS instance resource. Its master username and password use dynamic references to resolve values from 
  #SecretsManager. The dynamic reference guarantees that CloudFormation will not log or persist the resolved value 
  #We sub the Secret resource's logical id in order to construct the dynamic reference, since the Secret's name is being #generated by CloudFormation
  MyDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: A2OnLineMainDB
      AllocatedStorage: 20
      DBInstanceClass: db.t2.micro
      Engine: mysql
      # DBSubnetGroupName:
      #   Ref: MyDBSubnetGroup
      MasterUsername:
        Fn::Sub: "{{resolve:secretsmanager:${MyRDSInstanceRotationSecret}::username}}"
      MasterUserPassword:
        Fn::Sub: "{{resolve:secretsmanager:${MyRDSInstanceRotationSecret}::password}}"
      BackupRetentionPeriod: 1
      VPCSecurityGroups: 
      # ap-southeast-1
        # - sg-0972b7aabb5370b44         
      # SourceRegion: us-east-1
      # SourceDBInstanceIdentifier: arn:aws:rds:us-east-1:154096909498:db:a2onlinemaindb

      # us-east-1
        - sg-0984573a1a37c1d1a

        
  #Database subnet group for the RDS instance 
  # MyDBSubnetGroup:
  #   Type: AWS::RDS::DBSubnetGroup
  #   Properties:
  #     DBSubnetGroupDescription: DataBase Group
  #     SubnetIds:
  #     - subnet-17209e71
      
  #This is a SecretTargetAttachment resource which updates the referenced Secret resource with properties about
  #the referenced RDS instance
  SecretRDSInstanceAttachment:
    Type: AWS::SecretsManager::SecretTargetAttachment
    Properties:
      SecretId:
        Ref: MyRDSInstanceRotationSecret
      TargetId:
        Ref: MyDBInstance
      TargetType: AWS::RDS::DBInstance
  
  #This is a RotationSchedule resource. It configures rotation of password for the referenced secret using a rotation lambda function
  #The first rotation happens at resource creation time, with subsequent rotations scheduled according to the rotation rules
  #We explicitly depend on the SecretTargetAttachment resource being created to ensure that the secret contains all the
  #information necessary for rotation to succeed
  MySecretRotationSchedule:
    Type: AWS::SecretsManager::RotationSchedule
    DependsOn: SecretRDSInstanceAttachment
    Properties:
      SecretId:
        Ref: MyRDSInstanceRotationSecret
      HostedRotationLambda:
        RotationType: MySQLSingleUser
        RotationLambdaName: SecretsManagerRotation
        VpcSubnetIds: subnet-17209e71
      RotationRules:
        AutomaticallyAfterDays: 30

