---

Transform: Databse slave-2020-07-23
Description: database mysql slave
Resources:
  MyDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: a2onlinemaindb
      AllocatedStorage: 20
      DBInstanceClass: db.t2.micro
      Engine: mysql
      BackupRetentionPeriod: 1
      VPCSecurityGroups: 
        - sg-0972b7aabb5370b44         
      SourceRegion: us-east-1
      SourceDBInstanceIdentifier: arn:aws:rds:us-east-1:154096909498:db:a2onlinemaindb


