---
# This playbook deploys the whole application stack in this site.

- name: apply common configuration to all nodes
  hosts: all
  remote_user: root

  roles:
    - common

- name: install and configure nginx
  hosts: nginxservers
  remote_user: root
  roles:
    - role: nginx
      tags: 
        - nginx

- name: install and configure tomcat
  hosts: tomcatservers
  remote_user: root
  roles:
    - role: tomcat
      tags: 
        - tomcat

- name: build java project
  hosts: tomcatservers
  remote_user: root
  roles:
    - role: java
      tags: 
        - java
 

- name: deploy MySQL and configure the databases
  hosts: dbservers
  remote_user: root

  roles:
    - db
