---
- name: apt update
  apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 1800
  become: yes

- name: install tomcat9
  apt: name=tomcat9 state=latest
  become: yes
   
- name: ensure tomcat is running
  service: name=tomcat9 state=started
  become: yes



