---
# These tasks from common.

- name: debug from common
  debug:
    msg: "this task is from common debug"
  when: debug


# 2 * nginxservers

- include_tasks: provision_gateway.yml
  vars:
    server_type: nginxservers
    inst_count: 1
    ec2_group_name: zone_a_group
    subnet: subnet-0d48c844db4369b01
  when: initial
  tags:
    - nginx

- include_tasks: provision_gateway.yml
  vars:
    server_type: nginxservers
    inst_count: 1
    ec2_group_name: zone_b_group
    subnet: subnet-0a6f31ce699892394
  when: initial
  tags:
    - nginx

- include_tasks: ELB.yml
  when: initial
  tags:
    - nginx


# 2 * tomcatservers

- include_tasks: provision_internal.yml
  vars:
    server_type: tomcatservers    
    inst_count: 2
    ec2_group_name: zone_c_group
    subnet: subnet-0d2cf1aaf87f39d46
  when: initial


# 2 * webservers

#- include_tasks: provision.yml
#  vars:
#    server_type: webservers
#  when: initial

#- include_tasks: provision.yml
#  vars:
#    server_type: webservers
#  when: initial
 

- include_tasks: terminate.yml
  when: terminate 