---
# These tasks from common.

- name: debug from common
  debug:
    msg: "this task is from common debug"
  when: debug


# 2 * nginxservers

- include_tasks: provision1.yml
  vars:
    server_type: nginxservers
    inst_count: 1
  when: initial
  tags:
    - nginx

- include_tasks: provision2.yml
  vars:
    server_type: nginxservers
    inst_count: 1
  when: initial
  tags:
    - nginx

- include_tasks: ELB.yml
  when: initial
  tags:
    - nginx


# 2 * tomcatservers

- include_tasks: provision1.yml
  vars:
    server_type: tomcatservers    
    inst_count: 2
  when: initial


# 2 * webservers

#- include_tasks: provision.yml
#  vars:
#    server_type: webservers
#  when: initial

#- include_tasks: provision.yml
#  vars:
#    server_type: webservers
#  when: initial
 

- include_tasks: terminate.yml
  when: terminate 