---
 
- name: Create EC2 instance
  command: "aws ec2 run-instances --image-id ami-09e67e426f25ce0d7 --count {{inst_count}} --instance-type {{ instance_type }} --key-name ec2key --security-group-ids sg-0984573a1a37c1d1a --subnet-id subnet-07a9d9803eb8d6cb7"

- name: Sleep for 60 seconds
  pause:
    seconds: 60
   
- name: Get IP address of the newly created host so that we can further contact it
  shell: "aws ec2 describe-instances --query 'Reservations[*].Instances[*].[State.Name,InstanceId,PublicIpAddress]' --output text | grep running | awk '{print $3}'"
  register: ec2_ip
 

- name: Wait for SSH to come up
  wait_for:
    host: "{{ item }}"
    port: 22
    state: started
  loop: "{{ ec2_ip.stdout_lines }}"
