---

- name: Create a security group
  ec2_group:
    name: "zone_a_group"
    description: The security group from zone A
    region: "{{ region }}"
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 443
        to_port: 443
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 8080
        to_port: 8080
        cidr_ip: 172.31.0.0/16
    rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0
  register: ec2_sec_group

- name: Create EC2 instance
  command: "aws ec2 run-instances --image-id {{ image }} --count {{inst_count}} --instance-type {{ instance_type }} --key-name {{ ec2_key_name }} --security-group-ids {{ ec2_sec_group.group_id }}  --subnet-id subnet-c177d989"

- name: Sleep for 60 seconds
  pause:
    seconds: 60
   
- name: Get IP address of the newly created host so that we can further contact it
  shell: "aws ec2 describe-instances --query 'Reservations[*].Instances[*].[State.Name,InstanceId,PublicIpAddress]' --output text | grep running | awk '{print $3}'"
  register: ec2_ip
 

- name: Wait for SSH to come up
  wait_for:
    host: "{{ item }}"
    port: 22
    state: started
  loop: "{{ ec2_ip.stdout_lines }}"
